name: "Deploy to Server"

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SERVER_IP: ${{ vars.SERVER_IP }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - name: Build Docker Image
        run: |
          docker login -u alexdahal12 -p $DOCKERHUB_PAT
          docker build -t alexdahal12/mywebsite .
          docker push alexdahal12/mywebsite
        env:
          DOCKERHUB_PAT: ${{ secrets.DOCKERHUB_PAT }}

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo -e "Host *\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
          touch ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts

      - name: Setup SSH Key
        run: |
          echo "$SSH_KEY64" | base64 -d > pem.pem && chmod 400 pem.pem
          ssh-keygen -R $SERVER_IP
        env:
          SSH_KEY64: ${{ secrets.SSH_KEY64 }}

      - name: Deploy Docker Container
        run: |
          ssh -i pem.pem ubuntu@$SERVER_IP \
          'docker pull alexdahal12/mywebsite && \
           docker stop mywebsite || true && \
           docker rm mywebsite || true && \
           docker run -d --name mywebsite -p 80:80 alexdahal12/mywebsite'